import React from 'react';

class Pocket extends React.Component{
    
removePocket(e, price){
    this.props.removeFromPocket(e, price)
}
    
makeRows(){
    return this.props.pocket.map((item, index)=>{
        return <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[index] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[index].type}/${this.props.pocket[index].image}.png`} alt={this.props.pocket[index].item} value={index} onClick={e => this.removePocket(e.target.value, this.props.pocket[index].price)}/>}</div></td>
    })
}
    render(){
        return(
            <div className='myPocket'>
                <h2>My Pocket - <span>Value: {this.props.pocketValue}</span></h2>
                <div className='pocketContents'>
                    <table id='pocket-table'>
                        <tr className='pocket-row'>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[0] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[0].type}/${this.props.pocket[0].image}.png`} alt={this.props.pocket[0].item} value={0} onClick={e => this.removePocket(e.target.value, this.props.pocket[0].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[1] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[1].type}/${this.props.pocket[1].image}.png`} alt={this.props.pocket[1].item} value={1} onClick={e => this.removePocket(e.target.value, this.props.pocket[1].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[2] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[2].type}/${this.props.pocket[2].image}.png`} alt={this.props.pocket[2].item} value={2} onClick={e => this.removePocket(e.target.value, this.props.pocket[2].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[3] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[3].type}/${this.props.pocket[3].image}.png`} alt={this.props.pocket[3].item} value={3} onClick={e => this.removePocket(e.target.value, this.props.pocket[3].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[4] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[4].type}/${this.props.pocket[4].image}.png`} alt={this.props.pocket[4].item} value={4} onClick={e => this.removePocket(e.target.value, this.props.pocket[4].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[5] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[5].type}/${this.props.pocket[5].image}.png`} alt={this.props.pocket[5].item} value={5} onClick={e => this.removePocket(e.target.value, this.props.pocket[5].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[6] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[6].type}/${this.props.pocket[6].image}.png`} alt={this.props.pocket[6].item} value={6} onClick={e => this.removePocket(e.target.value, this.props.pocket[6].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[7] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[7].type}/${this.props.pocket[7].image}.png`} alt={this.props.pocket[7].item} value={7} onClick={e => this.removePocket(e.target.value, this.props.pocket[7].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[8] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[8].type}/${this.props.pocket[8].image}.png`} alt={this.props.pocket[8].item} value={8} onClick={e => this.removePocket(e.target.value, this.props.pocket[8].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[9] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[9].type}/${this.props.pocket[9].image}.png`} alt={this.props.pocket[9].item} value={9} onClick={e => this.removePocket(e.target.value, this.props.pocket[9].price)}/>}</div></td>
                        </tr>
                        <tr className='pocket-row'>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[10] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[10].type}/${this.props.pocket[10].image}.png`} alt={this.props.pocket[10].item} value={10} onClick={e => this.removePocket(e.target.value, this.props.pocket[10].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[11] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[11].type}/${this.props.pocket[11].image}.png`} alt={this.props.pocket[11].item} value={11} onClick={e => this.removePocket(e.target.value, this.props.pocket[11].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[12] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[12].type}/${this.props.pocket[12].image}.png`} alt={this.props.pocket[12].item} value={12} onClick={e => this.removePocket(e.target.value, this.props.pocket[12].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[13] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[13].type}/${this.props.pocket[13].image}.png`} alt={this.props.pocket[13].item} value={13} onClick={e => this.removePocket(e.target.value, this.props.pocket[13].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[14] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[14].type}/${this.props.pocket[14].image}.png`} alt={this.props.pocket[14].item} value={14} onClick={e => this.removePocket(e.target.value, this.props.pocket[14].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[15] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[15].type}/${this.props.pocket[15].image}.png`} alt={this.props.pocket[15].item} value={15} onClick={e => this.removePocket(e.target.value, this.props.pocket[15].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[16] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[16].type}/${this.props.pocket[16].image}.png`} alt={this.props.pocket[16].item} value={16} onClick={e => this.removePocket(e.target.value, this.props.pocket[16].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[17] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[17].type}/${this.props.pocket[17].image}.png`} alt={this.props.pocket[17].item} value={17} onClick={e => this.removePocket(e.target.value, this.props.pocket[17].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[18] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[18].type}/${this.props.pocket[18].image}.png`} alt={this.props.pocket[18].item} value={18} onClick={e => this.removePocket(e.target.value, this.props.pocket[18].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[19] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[19].type}/${this.props.pocket[19].image}.png`} alt={this.props.pocket[19].item} value={19} onClick={e => this.removePocket(e.target.value, this.props.pocket[19].price)}/>}</div></td>
                        </tr>
                        <tr className='pocket-row'>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[20] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[20].type}/${this.props.pocket[20].image}.png`} alt={this.props.pocket[20].item} value={20} onClick={e => this.removePocket(e.target.value, this.props.pocket[20].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[21] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[21].type}/${this.props.pocket[21].image}.png`} alt={this.props.pocket[21].item} value={21} onClick={e => this.removePocket(e.target.value, this.props.pocket[21].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[22] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[22].type}/${this.props.pocket[22].image}.png`} alt={this.props.pocket[22].item} value={22} onClick={e => this.removePocket(e.target.value, this.props.pocket[22].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[23] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[23].type}/${this.props.pocket[23].image}.png`} alt={this.props.pocket[23].item} value={23} onClick={e => this.removePocket(e.target.value, this.props.pocket[23].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[24] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[24].type}/${this.props.pocket[24].image}.png`} alt={this.props.pocket[24].item} value={24} onClick={e => this.removePocket(e.target.value, this.props.pocket[24].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[25] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[25].type}/${this.props.pocket[25].image}.png`} alt={this.props.pocket[25].item} value={25} onClick={e => this.removePocket(e.target.value, this.props.pocket[25].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[26] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[26].type}/${this.props.pocket[26].image}.png`} alt={this.props.pocket[26].item} value={26} onClick={e => this.removePocket(e.target.value, this.props.pocket[26].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[27] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[27].type}/${this.props.pocket[27].image}.png`} alt={this.props.pocket[27].item} value={27} onClick={e => this.removePocket(e.target.value, this.props.pocket[27].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[28] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[28].type}/${this.props.pocket[28].image}.png`} alt={this.props.pocket[28].item} value={28} onClick={e => this.removePocket(e.target.value, this.props.pocket[28].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[29] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[29].type}/${this.props.pocket[29].image}.png`} alt={this.props.pocket[29].item} value={29} onClick={e => this.removePocket(e.target.value, this.props.pocket[29].price)}/>}</div></td>
                        </tr>
                        <tr className='pocket-row'>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[30] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[30].type}/${this.props.pocket[30].image}.png`} alt={this.props.pocket[30].item} value={30} onClick={e => this.removePocket(e.target.value, this.props.pocket[30].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[31] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[31].type}/${this.props.pocket[31].image}.png`} alt={this.props.pocket[31].item} value={31} onClick={e => this.removePocket(e.target.value, this.props.pocket[31].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[32] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[32].type}/${this.props.pocket[32].image}.png`} alt={this.props.pocket[32].item} value={32} onClick={e => this.removePocket(e.target.value, this.props.pocket[32].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[33] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[33].type}/${this.props.pocket[33].image}.png`} alt={this.props.pocket[33].item} value={33} onClick={e => this.removePocket(e.target.value, this.props.pocket[33].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[34] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[34].type}/${this.props.pocket[34].image}.png`} alt={this.props.pocket[34].item} value={34} onClick={e => this.removePocket(e.target.value, this.props.pocket[34].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[35] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[35].type}/${this.props.pocket[35].image}.png`} alt={this.props.pocket[35].item} value={35} onClick={e => this.removePocket(e.target.value, this.props.pocket[35].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[36] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[36].type}/${this.props.pocket[36].image}.png`} alt={this.props.pocket[36].item} value={36} onClick={e => this.removePocket(e.target.value, this.props.pocket[36].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[37] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[37].type}/${this.props.pocket[37].image}.png`} alt={this.props.pocket[37].item} value={37} onClick={e => this.removePocket(e.target.value, this.props.pocket[37].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[38] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[38].type}/${this.props.pocket[38].image}.png`} alt={this.props.pocket[38].item} value={38} onClick={e => this.removePocket(e.target.value, this.props.pocket[38].price)}/>}</div></td>
                            <td className='pocketSlot'><div className='pocket-slot-empty'>{this.props.pocket[39] && <input type='image' className='pocketIcons' src={`/icons/${this.props.pocket[39].type}/${this.props.pocket[39].image}.png`} alt={this.props.pocket[39].item} value={39} onClick={e => this.removePocket(e.target.value, this.props.pocket[39].price)}/>}</div></td>        
                        </tr>
                    </table>
                </div>
            </div>
        )
    }
}

export default Pocket;
